//
// Generated file, do not edit! Created by nedtool 5.5 from Order.msg.
//

#ifndef __BARSIMULATOR_ORDER_M_H
#define __BARSIMULATOR_ORDER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace barsimulator {

/**
 * Class generated from <tt>Order.msg:21</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Order
 * {
 *     double index;
 *     double timestamp;
 *     int status;
 * }
 * </pre>
 */
class Order : public ::omnetpp::cPacket
{
  protected:
    double index;
    double timestamp;
    int status;

  private:
    void copy(const Order& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Order&);

  public:
    Order(const char *name=nullptr, short kind=0);
    Order(const Order& other);
    virtual ~Order();
    Order& operator=(const Order& other);
    virtual Order *dup() const override {return new Order(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getIndex() const;
    virtual void setIndex(double index);
    virtual double getTimestamp() const;
    virtual void setTimestamp(double timestamp);
    virtual int getStatus() const;
    virtual void setStatus(int status);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Order& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Order& obj) {obj.parsimUnpack(b);}

} // namespace barsimulator

#endif // ifndef __BARSIMULATOR_ORDER_M_H

