//
// Generated file, do not edit! Created by nedtool 5.5 from AircraftPacket.msg.
//

#ifndef __AERONAUTICALCOMMUNICATIONSIMULATOR_AIRCRAFTPACKET_M_H
#define __AERONAUTICALCOMMUNICATIONSIMULATOR_AIRCRAFTPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace aeronauticalcommunicationsimulator {

/**
 * Class generated from <tt>AircraftPacket.msg:21</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet AircraftPacket
 * {
 *     int aircraftID;
 *     double creationTime;
 * }
 * </pre>
 */
class AircraftPacket : public ::omnetpp::cPacket
{
  protected:
    int aircraftID;
    double creationTime;

  private:
    void copy(const AircraftPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AircraftPacket&);

  public:
    AircraftPacket(const char *name=nullptr, short kind=0);
    AircraftPacket(const AircraftPacket& other);
    virtual ~AircraftPacket();
    AircraftPacket& operator=(const AircraftPacket& other);
    virtual AircraftPacket *dup() const override {return new AircraftPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getAircraftID() const;
    virtual void setAircraftID(int aircraftID);
    virtual double getCreationTime() const;
    virtual void setCreationTime(double creationTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AircraftPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AircraftPacket& obj) {obj.parsimUnpack(b);}

} // namespace aeronauticalcommunicationsimulator

#endif // ifndef __AERONAUTICALCOMMUNICATIONSIMULATOR_AIRCRAFTPACKET_M_H

