//
// Generated file, do not edit! Created by nedtool 5.5 from DiscoveryMessage.msg.
//

#ifndef __AERONAUTICALCOMMUNICATIONSIMULATOR_DISCOVERYMESSAGE_M_H
#define __AERONAUTICALCOMMUNICATIONSIMULATOR_DISCOVERYMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace aeronauticalcommunicationsimulator {

/**
 * Class generated from <tt>DiscoveryMessage.msg:21</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet DiscoveryMessage
 * {
 *     int bsID;
 *     double x;
 *     double y;
 * }
 * </pre>
 */
class DiscoveryMessage : public ::omnetpp::cPacket
{
  protected:
    int bsID;
    double x;
    double y;

  private:
    void copy(const DiscoveryMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DiscoveryMessage&);

  public:
    DiscoveryMessage(const char *name=nullptr, short kind=0);
    DiscoveryMessage(const DiscoveryMessage& other);
    virtual ~DiscoveryMessage();
    DiscoveryMessage& operator=(const DiscoveryMessage& other);
    virtual DiscoveryMessage *dup() const override {return new DiscoveryMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getBsID() const;
    virtual void setBsID(int bsID);
    virtual double getX() const;
    virtual void setX(double x);
    virtual double getY() const;
    virtual void setY(double y);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DiscoveryMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DiscoveryMessage& obj) {obj.parsimUnpack(b);}

} // namespace aeronauticalcommunicationsimulator

#endif // ifndef __AERONAUTICALCOMMUNICATIONSIMULATOR_DISCOVERYMESSAGE_M_H

